
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "shravan_prajapati",
  "name": "Shravan Prajapati",
  "password": "shra_567",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "shravan_prajapati",
  "password": "shra_567"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "shravan_prajapati",
  "oldPassword": "shra_567",
  "newPassword": "shra@123"
}



